#!/usr/bin/env python3
"""Validate the Android v0.4 release candidate manifest summary.

This verifier is read-only. It checks that the pre-tag manifest generated by
verify-v0.4-release-candidate-manifest.sh still exposes the fields that release
review depends on: component summaries, no-publish/no-stage guarantees,
redaction status, schema status, git-index preservation, version blocker, and
public batch boundaries.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path


COMPONENT_SUMMARY_KEYS = (
    "release readiness summary",
    "archive consumer summary",
    "publish workflow summary",
    "public commit scope summary",
    "public release batch summary",
    "public release batch schema summary",
    "version bump plan summary",
    "version bump dry-run summary",
)


def strip_value(value: str) -> str:
    value = value.strip()
    if value.startswith("`") and value.endswith("`"):
        return value[1:-1]
    return value


def read_values(summary_path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    pattern = re.compile(r"^- ([^:]+):\s*(.*)$")
    for line in summary_path.read_text(encoding="utf-8").splitlines():
        match = pattern.match(line)
        if match:
            values.setdefault(match.group(1), strip_value(match.group(2)))
    return values


def read_section(summary_path: Path, heading: str) -> list[str]:
    items: list[str] = []
    in_section = False
    for line in summary_path.read_text(encoding="utf-8").splitlines():
        if line == f"## {heading}":
            in_section = True
            continue
        if in_section and line.startswith("## "):
            break
        if in_section and line.startswith("- "):
            items.append(line[2:])
    return items


def fail(failures: list[str], message: str) -> None:
    failures.append(message)


def expect_value(failures: list[str], values: dict[str, str], key: str, expected: str) -> None:
    if values.get(key) != expected:
        fail(failures, f"{key} must be {expected}; got {values.get(key, '<missing>')}")


def expect_path(failures: list[str], values: dict[str, str], key: str) -> Path | None:
    value = values.get(key, "")
    if not value.startswith("/"):
        fail(failures, f"{key} must be an absolute path")
        return None
    path = Path(value)
    if not path.exists():
        fail(failures, f"{key} path does not exist: {path}")
        return None
    return path


def expect_positive_int(failures: list[str], values: dict[str, str], key: str) -> None:
    value = values.get(key, "")
    try:
        number = int(value)
    except ValueError:
        fail(failures, f"{key} must be an integer")
        return
    if number < 0:
        fail(failures, f"{key} must be non-negative")


def expect_sha256(failures: list[str], values: dict[str, str], key: str) -> None:
    value = values.get(key, "")
    if not re.fullmatch(r"[0-9a-f]{64}", value):
        fail(failures, f"{key} must be a SHA-256 digest")


def main() -> int:
    summary_arg = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("LEONA_V04_RELEASE_CANDIDATE_SUMMARY")
    out_dir = Path(os.environ.get("LEONA_V04_RELEASE_CANDIDATE_SCHEMA_OUT", "/tmp/leona-v0.4-release-candidate-schema"))
    target_version = os.environ.get("LEONA_TARGET_RELEASE_VERSION", "0.4.0")
    out_dir.mkdir(parents=True, exist_ok=True)
    schema_summary = out_dir / "summary.md"

    failures: list[str] = []
    warnings: list[str] = []

    if not summary_arg:
        fail(failures, "missing release candidate summary path")
        values: dict[str, str] = {}
        summary_path = None
    else:
        summary_path = Path(summary_arg)
        if not summary_path.is_file():
            fail(failures, f"release candidate summary does not exist: {summary_path}")
            values = {}
        else:
            values = read_values(summary_path)

    if values:
        status = values.get("status")
        sdk_version = values.get("SDK coordinate version")
        require_pretag = values.get("require pre-tag ready")
        redaction_status = values.get("release evidence pack redaction scan")

        if status not in {"local-pass-with-external-blockers", "failed"}:
            fail(failures, "status must be local-pass-with-external-blockers or failed")
        if values.get("target release version") != target_version:
            fail(failures, f"target release version must be {target_version}")
        if not sdk_version:
            fail(failures, "SDK coordinate version must be present")
        if require_pretag not in {"0", "1"}:
            fail(failures, "require pre-tag ready must be 0 or 1")
        if redaction_status not in {"pass", "failed"}:
            fail(failures, "release evidence pack redaction scan must be pass or failed")

        expect_path(failures, values, "report dir")
        expect_path(failures, values, "release evidence pack")
        expect_path(failures, values, "release evidence pack json")
        expect_path(failures, values, "release evidence pack schema summary")
        expect_path(failures, values, "git index before")
        expect_path(failures, values, "git index after")
        for key in COMPONENT_SUMMARY_KEYS:
            expect_path(failures, values, key)

        expect_value(failures, values, "secret values printed", "no")
        expect_value(failures, values, "creates tag", "no")
        expect_value(failures, values, "triggers GitHub Actions", "no")
        expect_value(failures, values, "publishes artifacts", "no")
        expect_value(failures, values, "executes git add", "no")
        expect_value(failures, values, "starts paid devices or WeTest sessions", "no")
        expect_value(failures, values, "release evidence pack schema status", "pass")
        expect_value(failures, values, "release candidate preserves git index", "yes")
        expect_value(failures, values, "public release batch schema status", "pass")
        expect_value(failures, values, "public release batch stage command draft syntax", "pass")
        expect_value(failures, values, "public release batch stage command draft matches public batch", "yes")
        expect_value(failures, values, "public release batch stage command draft contains do-not-stage paths", "no")
        expect_value(failures, values, "public release batch stage command dry-run", "pass")
        expect_value(failures, values, "public release batch stage command dry-run preserves index", "yes")
        expect_value(failures, values, "version bump plan status", "pass")
        expect_value(failures, values, "version bump dry-run status", "pass")

        for key in (
            "release readiness local pass checks",
            "public release batch paths",
            "public release batch do-not-stage paths",
            "public release batch staged forbidden paths",
            "public release batch stage command draft paths",
        ):
            expect_positive_int(failures, values, key)

        expect_value(failures, values, "public release batch staged forbidden paths", "0")
        for key in (
            "public release batch paths sha256",
            "public release batch do-not-stage paths sha256",
            "public release batch staged forbidden paths sha256",
            "public release batch stage command draft paths sha256",
        ):
            expect_sha256(failures, values, key)
        if values.get("public release batch paths sha256") != values.get("public release batch stage command draft paths sha256"):
            fail(failures, "public batch path hash must match stage draft path hash")

        failures_section = read_section(summary_path, "Failures") if summary_path else []
        pretag_blockers = read_section(summary_path, "Pre-Tag Blockers") if summary_path else []
        external_blockers = read_section(summary_path, "External Blockers") if summary_path else []

        if status == "local-pass-with-external-blockers" and failures_section != ["none"]:
            fail(failures, "local-pass manifest must list no failures")
        if status == "failed" and failures_section == ["none"]:
            fail(failures, "failed manifest must list at least one failure")
        if sdk_version != target_version:
            if pretag_blockers == ["none"]:
                fail(failures, "version mismatch must be listed as a pre-tag blocker")
        if require_pretag == "1" and sdk_version != target_version:
            if status != "failed":
                fail(failures, "strict pre-tag mode with version mismatch must fail")
            if not any("pre-tag readiness required" in item for item in failures_section):
                fail(failures, "strict pre-tag failure must mention pre-tag readiness")
        if not external_blockers:
            warnings.append("external blockers section is empty")

        forbidden_runtime_keys = (
            "createsTag",
            "triggersGitHubActions",
            "publishesArtifacts",
            "startsPaidDevices",
            "startsWeTestSessions",
            "executesGitAdd",
            "printsSecrets",
        )
        text = summary_path.read_text(encoding="utf-8") if summary_path else ""
        for key in forbidden_runtime_keys:
            if re.search(rf'"?{re.escape(key)}"?\s*:\s*true', text):
                fail(failures, f"{key} must not be true in release candidate manifest")

    status = "pass" if not failures else "failed"
    with schema_summary.open("w", encoding="utf-8") as handle:
        handle.write("# Leona v0.4 Android Release Candidate Manifest Schema\n\n")
        handle.write(f"- status: {status}\n")
        handle.write(f"- release candidate summary: `{summary_arg or ''}`\n")
        handle.write("- validates component summaries: yes\n")
        handle.write("- validates no-auto-stage/no-publish/no-device rules: yes\n")
        handle.write("- validates public release batch fields: yes\n")
        handle.write("- validates evidence pack schema status: yes\n")
        handle.write("- validates version blocker contract: yes\n")
        handle.write("- secret values printed: no\n")
        handle.write("- creates tag: no\n")
        handle.write("- triggers GitHub Actions: no\n")
        handle.write("- publishes artifacts: no\n")
        handle.write("- executes git add: no\n")
        handle.write("- starts paid devices or WeTest sessions: no\n\n")
        handle.write("## Warnings\n")
        if warnings:
            for warning in warnings:
                handle.write(f"- {warning}\n")
        else:
            handle.write("- none\n")
        handle.write("\n## Failures\n")
        if failures:
            for failure in failures:
                handle.write(f"- {failure}\n")
        else:
            handle.write("- none\n")

    print(f"[release-candidate-schema] summary: {schema_summary}")
    return 0 if status == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
