#!/usr/bin/env python3
"""Validate the Android v0.4 release evidence pack JSON structure.

This is a local, public-safe pre-tag verifier. It validates structure,
file digests, byte counts, and Markdown/JSON parity for the evidence pack
generated by verify-v0.4-release-candidate-manifest.sh. It does not require
redactionScan to be "pass" so synthetic redaction negative tests still fail
only on the redaction gate itself.
"""

from __future__ import annotations

import hashlib
import json
import os
import sys
from pathlib import Path
from typing import Any


EXPECTED_COMPONENTS = [
    "release readiness",
    "archive consumer",
    "publish workflow",
    "public commit scope",
    "public release batch",
    "public release batch schema",
    "version bump plan",
    "version bump dry-run",
]


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def fail(failures: list[str], message: str) -> None:
    failures.append(message)


def require_type(failures: list[str], obj: Any, key: str, expected_type: type) -> Any:
    if key not in obj:
        fail(failures, f"missing key: {key}")
        return None
    value = obj[key]
    if not isinstance(value, expected_type):
        fail(failures, f"{key} must be {expected_type.__name__}")
        return None
    return value


def validate_file_entry(
    failures: list[str],
    label: str,
    path_value: Any,
    sha_value: Any,
    bytes_value: Any,
) -> None:
    if not isinstance(path_value, str) or not path_value.startswith("/"):
        fail(failures, f"{label} path must be absolute")
        return
    path = Path(path_value)
    if not path.is_file():
        fail(failures, f"{label} path does not exist: {path}")
        return
    if not isinstance(sha_value, str) or len(sha_value) != 64:
        fail(failures, f"{label} sha256 must be a 64-character hex digest")
    elif sha256(path) != sha_value:
        fail(failures, f"{label} sha256 mismatch: {path}")
    if not isinstance(bytes_value, int) or bytes_value < 0:
        fail(failures, f"{label} bytes must be a non-negative integer")
    elif path.stat().st_size != bytes_value:
        fail(failures, f"{label} byte count mismatch: {path}")


def main() -> int:
    json_arg = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("LEONA_V04_EVIDENCE_PACK_JSON")
    out_dir = Path(os.environ.get("LEONA_V04_EVIDENCE_PACK_SCHEMA_OUT", "/tmp/leona-v0.4-evidence-pack-schema"))
    target_version = os.environ.get("LEONA_TARGET_RELEASE_VERSION", "0.4.0")
    out_dir.mkdir(parents=True, exist_ok=True)
    summary_path = out_dir / "summary.md"

    failures: list[str] = []
    warnings: list[str] = []

    if not json_arg:
        fail(failures, "missing evidence pack json path")
        json_path = None
        data = {}
    else:
        json_path = Path(json_arg)
        if not json_path.is_file():
            fail(failures, f"evidence pack json does not exist: {json_path}")
            data = {}
        else:
            try:
                data = json.loads(json_path.read_text(encoding="utf-8"))
            except Exception as exc:  # noqa: BLE001 - summary should include parser reason.
                fail(failures, f"invalid JSON: {exc}")
                data = {}

    if not isinstance(data, dict):
        fail(failures, "top-level JSON value must be an object")
        data = {}

    if data:
        target = require_type(failures, data, "targetReleaseVersion", str)
        sdk_version = require_type(failures, data, "sdkCoordinateVersion", str)
        report_dir = require_type(failures, data, "reportDir", str)
        secret_values_printed = require_type(failures, data, "secretValuesPrinted", bool)
        redaction_scan = require_type(failures, data, "redactionScan", str)
        redaction_log = require_type(failures, data, "redactionScanLog", str)
        git_index_preserved = require_type(failures, data, "gitIndexPreserved", str)
        git_index = require_type(failures, data, "gitIndex", dict)
        components = require_type(failures, data, "components", list)

        if target != target_version:
            fail(failures, f"targetReleaseVersion must be {target_version}")
        if sdk_version and not isinstance(sdk_version, str):
            fail(failures, "sdkCoordinateVersion must be a string")
        if not isinstance(report_dir, str) or not report_dir.startswith("/"):
            fail(failures, "reportDir must be absolute")
        elif not Path(report_dir).is_dir():
            fail(failures, f"reportDir does not exist: {report_dir}")
        if secret_values_printed is not False:
            fail(failures, "secretValuesPrinted must be false")
        if redaction_scan not in {"pass", "failed"}:
            fail(failures, "redactionScan must be pass or failed")
        if git_index_preserved not in {"yes", "no"}:
            fail(failures, "gitIndexPreserved must be yes or no")
        if isinstance(redaction_log, str) and redaction_log:
            redaction_log_path = Path(redaction_log)
            if not redaction_log_path.is_absolute():
                fail(failures, "redactionScanLog must be absolute")
            elif not redaction_log_path.exists():
                fail(failures, f"redactionScanLog does not exist: {redaction_log_path}")

        forbidden_runtime_keys = {
            "createsTag",
            "triggersGitHubActions",
            "publishesArtifacts",
            "startsPaidDevices",
            "startsWeTestSessions",
            "executesGitAdd",
            "printsSecrets",
        }
        for key in forbidden_runtime_keys:
            if data.get(key) is True:
                fail(failures, f"{key} must not be true in local evidence pack")

        if isinstance(git_index, dict):
            validate_file_entry(
                failures,
                "git index before",
                git_index.get("beforePath"),
                git_index.get("beforeSha256"),
                git_index.get("beforeBytes"),
            )
            validate_file_entry(
                failures,
                "git index after",
                git_index.get("afterPath"),
                git_index.get("afterSha256"),
                git_index.get("afterBytes"),
            )

        if isinstance(components, list):
            names = [item.get("name") for item in components if isinstance(item, dict)]
            if names != EXPECTED_COMPONENTS:
                fail(failures, f"components must be exactly: {', '.join(EXPECTED_COMPONENTS)}")
            for item in components:
                if not isinstance(item, dict):
                    fail(failures, "component entries must be objects")
                    continue
                validate_file_entry(
                    failures,
                    f"component {item.get('name', '<unknown>')}",
                    item.get("summaryPath"),
                    item.get("sha256"),
                    item.get("bytes"),
                )

        if json_path is not None:
            md_path = json_path.with_suffix(".md")
            if not md_path.is_file():
                fail(failures, f"evidence pack markdown sibling missing: {md_path}")
            else:
                md_text = md_path.read_text(encoding="utf-8")
                parity_markers = [
                    str(target),
                    str(sdk_version),
                    str(redaction_scan),
                    str(git_index_preserved),
                    "Component Summaries",
                    "Git Index Snapshots",
                    "does not create tags",
                    "publish artifacts",
                    "print secrets",
                ]
                for marker in parity_markers:
                    if marker and marker not in md_text:
                        fail(failures, f"markdown parity marker missing: {marker}")
                for name in EXPECTED_COMPONENTS:
                    if name not in md_text:
                        fail(failures, f"markdown missing component: {name}")

    status = "pass" if not failures else "failed"
    with summary_path.open("w", encoding="utf-8") as handle:
        handle.write("# Leona v0.4 Android Release Evidence Pack Schema\n\n")
        handle.write(f"- status: {status}\n")
        handle.write(f"- evidence pack json: `{json_arg or ''}`\n")
        handle.write("- validates redaction scan status value: yes\n")
        handle.write("- requires redaction scan pass: no\n")
        handle.write("- secret values printed: no\n")
        handle.write("- creates tag: no\n")
        handle.write("- triggers GitHub Actions: no\n")
        handle.write("- publishes artifacts: no\n")
        handle.write("- starts paid devices or WeTest sessions: no\n\n")
        handle.write("## Expected Components\n")
        for name in EXPECTED_COMPONENTS:
            handle.write(f"- {name}\n")
        handle.write("\n## Warnings\n")
        if warnings:
            for warning in warnings:
                handle.write(f"- {warning}\n")
        else:
            handle.write("- none\n")
        handle.write("\n## Failures\n")
        if failures:
            for failure in failures:
                handle.write(f"- {failure}\n")
        else:
            handle.write("- none\n")

    print(f"[evidence-pack-schema] summary: {summary_path}")
    return 0 if status == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
